sudo: false
language: node_js
node_js:
  - '0.10'

notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change

before_install:
  - 'npm install -g tsd bower webpack wiredep'

script:
  - 'npm install'
